# Generated by Django 4.2.28 on 2026-03-02 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent account for sub-account grouping', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='general_ledger.chartofaccount'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_number'], name='gl_journale_entry_n_156b31_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='gl_journale_date_bf7dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['status'], name='gl_journale_status_276c50_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['code'], name='gl_chartofa_code_93fe27_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['account_type'], name='gl_chartofa_account_ae5f6d_idx'),
        ),
    ]
