# Generated by Django 4.2.28 on 2026-03-02 22:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('description', models.CharField(help_text='e.g., Tuition Fee - Semester 1, 2025', max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='unpaid', max_length=20)),
                ('due_date', models.DateField()),
                ('academic_year', models.CharField(help_text='e.g., 2025/2026', max_length=20)),
                ('term', models.CharField(blank=True, help_text='e.g., Semester 1, Term 2', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'ar_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LateFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rule name (e.g., Standard Late Fee)', max_length=100)),
                ('grace_period_days', models.PositiveIntegerField(default=7, help_text='Number of days after due date before late fee applies')),
                ('rate_type', models.CharField(choices=[('percentage', 'Percentage of Invoice Amount'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('rate_value', models.DecimalField(decimal_places=2, help_text='Percentage rate (e.g., 2.5%) or fixed amount', max_digits=10)),
                ('max_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum late fee cap (optional)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Late Fee Rule',
                'verbose_name_plural': 'Late Fee Rules',
                'db_table': 'ar_latefeerule',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('card', 'Card Payment'), ('other', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Payment reference / receipt number', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('payment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'ar_payment',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Institutional student ID (e.g., STU-2025-001)', max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('program', models.CharField(help_text='Degree program or course of study', max_length=200)),
                ('year_level', models.PositiveIntegerField(default=1, help_text='Current academic year/level')),
                ('enrollment_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'ar_student',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('invoice', 'Invoice (Charge)'), ('payment', 'Payment'), ('late_fee', 'Late Fee'), ('adjustment', 'Adjustment'), ('refund', 'Refund')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount charged (increases balance owed)', max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid/credited (decreases balance owed)', max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Running balance after this transaction', max_digits=12)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='accounts_receivable.student')),
            ],
            options={
                'verbose_name': 'Student Ledger Entry',
                'verbose_name_plural': 'Student Ledger Entries',
                'db_table': 'ar_studentledger',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='ar_student_student_c6aeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name', 'first_name'], name='ar_student_last_na_96aa21_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts_receivable.invoice'),
        ),
    ]
