# Generated by Django 4.2.28 on 2026-03-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_receivable', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
        migrations.AddField(
            model_name='student',
            name='class_category',
            field=models.CharField(choices=[('kindergarten', 'Kindergarten'), ('primary', 'Primary'), ('jhs', 'JHS')], default='primary', help_text='Current school section (e.g., Primary)', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, default='', help_text='Specific class (e.g., Class 1A, JHS 3B)', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_level',
            field=models.PositiveIntegerField(default=1, help_text='Numerical level (1 for Class 1, 2 for Class 2, etc.)'),
        ),
    ]
