# Generated by Django 4.2.28 on 2026-03-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_receivable', '0004_feestructure_teachersalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, help_text='Institutional student ID (e.g., KG-2025-001)', max_length=30, unique=True),
        ),
    ]
