# Generated by Django 4.2.28 on 2026-03-24 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_receivable', '0005_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['-academic_year', 'term', 'category'], 'verbose_name': 'Fee Structure', 'verbose_name_plural': 'Fee Structures'},
        ),
        migrations.AddField(
            model_name='feestructure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feestructure',
            name='name',
            field=models.CharField(default='Standard Fee', max_length=100),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='term',
            field=models.CharField(default='Term 1', max_length=20),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='category',
            field=models.CharField(choices=[('kindergarten', 'Kindergarten'), ('primary', 'Primary'), ('jhs', 'JHS')], max_length=20),
        ),
    ]
