# Generated by Django 4.2.28 on 2026-03-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('accountant', 'Accountant'), ('auditor', 'Auditor'), ('teacher', 'Teacher')], max_length=50, unique=True),
        ),
    ]
