# Generated by Django 4.2.28 on 2026-03-02 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts_payable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseapproval',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseapproval',
            name='expense',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='accounts_payable.expense'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounts_payable.expensecategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounts_payable.vendor'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status'], name='ap_expense_status_3e3010_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date'], name='ap_expense_expense_1cefdc_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['vendor'], name='ap_expense_vendor__2d409b_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='ap_expense_categor_03fa66_idx'),
        ),
    ]
